add more s3 helper functions
terascope/file-assets pull request #798
Opened 2023-06-02 19:21 UTC by lesleydreyer

adds a couple more s3 helper functions

- putS3Tagging
- deleteS3Objects
- doesBucketExist

2023-06-02 20:18 UTC, jsnoble approved these changes

2023-06-06 18:28 UTC, godber commented
I've looked at the versions you've set at this point and I think that looks good.  You all have my approval to release this once Jared is happy with the PR/tests.

2023-06-06 18:42 UTC, jsnoble requested changes

2023-06-06 18:42 UTC, jsnoble commented on packages/file-asset-apis/src/s3/s3-helpers.ts
> +    const command = (isV2ListParams(params) || useV2)
We should only have one form or the other.

2023-06-06 21:19 UTC, jsnoble approved these changes

2023-06-06 21:19 UTC, merged