Add S3 connector setup instructions to README.md
terascope/file-assets pull request #852
Opened 2023-10-03 19:46 UTC by busma13

Updated README.md with the following additions:
- Getting Started: commands to install teraslice-cli and deploy assets
- Connectors: config options table and example
- Development: test and build instructions

2023-10-03 20:06 UTC, busma13 commented
I don't have a good description for the `bucketEndpoint` property. Any idea what this does?

2023-10-03 20:11 UTC, godber commented
> I don't have a good description for the `bucketEndpoint` property. Any idea what this does?

It is passed through to the AWS S3 client library I think:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-middleware-bucket-endpoint/Interface/BucketEndpointInputConfig/

Though now I'm a little confused how we support two mutually exclusive booleans:

* `bucketEndpoint` - "Whether to use the bucket name as the endpoint for this request. The bucket name must be a domain name with a CNAME record alias to an appropriate virtual hosted-style S3 hostname, e.g. a bucket of images.johnsmith.net and a DNS record of:"
* `forcePathStyle` - "Whether to force path style URLs for S3 objects (e.g., https://s3.amazonaws.com/<bucketName>/<key> instead of https://<bucketName>.s3.amazonaws.com/<key>"

Do we enforce the fact that they are mutually exclusive?  I don't even seen `bucketEndpoint` in our code.

2023-10-03 20:15 UTC, godber commented
Here is `bucketEndpoint` in terafoundation:

https://github.com/search?q=repo%3Aterascope%2Fteraslice%20bucketEndpoint&type=code

2023-10-04 19:41 UTC, godber requested changes

2023-10-04 19:41 UTC, godber commented on README.md
> +**IMPORTANT:** Additionally make sure have installed the required [connectors](#connectors).
You should remove this comment, there's no additional connector in this case.

2023-10-04 19:41 UTC, godber commented on README.md
> +The terafoundation level S3 configuration is as follows:
```suggestion
The S3 connector configuration, in your Teraslice configuration file, includes the following parameters:
```

2023-10-04 19:41 UTC, godber commented on README.md
> +| endpoint | Target S3 endpoint | String | defaults to `127.0.0.1:80`
```suggestion
| endpoint | Target S3 HTTP endpoint, must be URL | String | defaults to `http://127.0.0.1:80` |
```

Add final `|` and make a proper URL

2023-10-16 21:16 UTC, godber approved these changes

2023-10-16 21:16 UTC, merged